export {
  getDb,
  upsertDocument,
  getDocumentByPath,
  getAllDocuments,
  deleteDocument,
  insertChunks,
  getChunksByDocumentId,
  deleteChunksByDocumentId,
  getStats,
  clearAll,
  dbHealthCheck,
  insertEntities,
  insertEntityRelations,
  getEntities,
  getEntityById,
  getEntityRelations,
  getChunkById,
  deleteEntitiesByChunkId,
  deleteEntitiesByDocumentId,
  createIndexSnapshot,
  getEntityStats,
  getEntitiesWithDocumentPath,
  getLatestSnapshot,
  getRecentSnapshots,
  updateSnapshotChangeDelta,
  updateEntityLastSeen,
  updateEntityResolved,
  getChunkDocumentPathMap,
  insertRiskItem,
  getRiskItems,
  getRiskById,
  dismissRisk,
  resolveRisksByType,
  getActiveRiskByTypeAndEntity,
  clearRiskItems,
  getRiskStats,
} from "./db";
export type { DocumentRow, ChunkRow, EntityRow, EntityRelationRow, IndexSnapshotRow, RiskItemRow } from "./db";
export {
  addChunks,
  querySimilarChunks,
  deleteDocumentChunks,
  resetCollection,
  getCollectionStats,
  chromaHealthCheck,
} from "./vectorstore";
